spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/healthcare
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        default_schema: hospitaldoctor
  redis:
    host: localhost
    port: 6379
    time-to-live: 300000
  cache:
    type: redis

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

server:
  port: 8080

logging:
  level:
    com.zaxxer.hikari: OFF
    org.hibernate: WARN