spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/healthcare
    username: postgres
    password: ****
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        default_schema: hospitaldoctor

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

server:
  port: 8080

logging:
  level:
    com.zaxxer.hikari: OFF
    org.hibernate: WARN
